name: Import EC2 AMI to AWS WorkSpaces

on:
  push:
    branches:
      - main

jobs:
  import-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Configure AWS CLI
        run: |
          aws configure set sso_start_url https://e360-ent.awsapps.com/start#/
          aws configure set sso_region us-west-2
          aws configure set region us-west-2
          aws configure set sso_role_name e360-AdministratorAccess

      - name: Run import script
        run: |
          python import_to_workspaces.py
