name: Build AMI

on:
  push:
    branches:
      - main

jobs:
  build_AMI:
    runs-on: ubuntu-latest
    environment: test #Github env name

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        packer-version: 'latest' # Specify the desired Packer version
  
    - name: Initialize Packer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: packer init ./aws-ubuntu.pkr.hcl

    - name: Build AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: packer build ./aws-ubuntu.pkr.hcl

  import_image:
    needs: build_AMI
    runs-on: ubuntu-latest
    environment: test #Github env name
    if: success()
    
    steps:
      - name: Importing image to AWS and converting to WSI image
        run: echo "Importing image to AWS and converting to WSI image"

  Workspace_create:
    needs: import_image
    runs-on: ubuntu-latest
    environment: test #Github env name
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2  # Replace with your AWS region

      - name: Execute Step Function
        run: |
          aws stepfunctions start-execution --state-machine-arn arn:aws:states:us-west-2:950694031822:stateMachine:MyStateMachine-pejsvpgtc  # Replace with your Step Function ARN
          echo "Step Function executed"



